### ISSUE TITLE
Checklist for Template 10 Snippet Pack VSIX

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1294]
There are already several T10 templates, but none of them are in the gallery yet. Some will be deleted, some will be added. Then, when they are ready, I will publish a Template Pack to the gallery. These will be updated for Template 10.2 only after it is stable.

## CSharp

- [x] T10_Property, creates a simple INPC property
- [x] T10_PropertyObservable, creates an ObservableCollection<T> property
- [x] T10_Event, creates an event and its Raise() method
- [x] T10_EventTyped, creates a typed event and its Raise() method
- [x] T10_Command, creates a relay command property
- [x] T10_CommandTyped, creates a typed relay command property
- [ ] T10_ViewModel, creates a shell view-model with overrides
- [ ] T10_ViewModelSample, creates a view-model with sample Items & SelectedItem
- [x] T10_Singleton, creates a singleton class

## XAML

- [ ] T10_Page, creates the basic page with visual states
- [ ] T10_Control_Resizer, creates a simple Resizer implementation
- [ ] T10_Control_PageHeader, creates a simple PageHeader implementation
- [ ] T10_Control_ModalDialog, creates a simple ModalDialog implementation

**Comment by syaifulnizamyahya** [comment]
XAML snippet would be very helpful.

Thanks.

**Comment by Tudball** [comment]
XAML Actions and Behavior blocks would make great snippets.
